import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useState } from 'react';
import { useDataStore } from '../store/dataStore';
import { useLocation } from 'react-router-dom';
import ExcelJS from 'exceljs';
export default function Billing() {
    const { patients, visits, updateVisit } = useDataStore();
    const location = useLocation();
    const pre = location.state?.patient;
    const [pid, setPid] = useState(pre?.id || '');
    const [bill, setBill] = useState(null);
    const patient = patients.find(p => p.id === pid);
    function generateBill() {
        if (!pid)
            return alert('Please select a patient');
        const pvs = visits.filter(v => v.patientId === pid && v.status === 'completed');
        const total = pvs.reduce((s, v) => s + v.charge, 0);
        const paid = pvs.filter(v => v.isPaid).reduce((s, v) => s + v.charge, 0);
        const rows = pvs.map((v, i) => {
            const dt = new Date(v.startTime);
            const date = dt.toLocaleDateString('en-IN');
            const dur = v.durationMin ? `${v.durationMin}m` : '—';
            return `${String(i + 1).padEnd(3)} ${date.padEnd(14)} ${dur.padEnd(6)} ₹${v.charge}`;
        });
        setBill([
            `════════════════════════════════════════`,
            `   🩺  PhyJio | Home Physiotherapy`,
            `              INVOICE`,
            `════════════════════════════════════════`,
            `Patient : ${patient?.fullName}`,
            `Age     : ${patient?.age} years`,
            `Ailment : ${patient?.ailment}`,
            `Date    : ${new Date().toLocaleDateString('en-IN')}`,
            `────────────────────────────────────────`,
            `No. Date           Dur    Amount`,
            `────────────────────────────────────────`,
            ...rows,
            `────────────────────────────────────────`,
            `TOTAL BILLED :           ₹${total}`,
            `Amount Paid  :           ₹${paid}`,
            `BALANCE DUE  :           ₹${total - paid}`,
            `════════════════════════════════════════`,
            `  Generated by PhyJio`,
            `  ${new Date().toLocaleString('en-IN')}`,
            `════════════════════════════════════════`,
        ].join('\n'));
    }
    async function exportExcel() {
        const wb = new ExcelJS.Workbook();
        const ws = wb.addWorksheet('PhyJio Visits');
        ws.columns = [
            { header: 'Date', key: 'date', width: 16 },
            { header: 'Patient', key: 'patient', width: 24 },
            { header: 'Ailment', key: 'ailment', width: 20 },
            { header: 'Duration', key: 'duration', width: 12 },
            { header: 'Charge', key: 'charge', width: 12 },
            { header: 'Paid', key: 'paid', width: 10 },
        ];
        // Style header row
        ws.getRow(1).eachCell(cell => {
            cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF008080' } };
            cell.font = { bold: true, color: { argb: 'FFFFFFFF' } };
        });
        // Add data
        const src = pid
            ? visits.filter(v => v.patientId === pid && v.status === 'completed')
            : visits.filter(v => v.status === 'completed');
        src.forEach(v => {
            const p = patients.find(x => x.id === v.patientId);
            ws.addRow({
                date: new Date(v.startTime).toLocaleDateString('en-IN'),
                patient: p?.fullName || 'Unknown',
                ailment: p?.ailment || '—',
                duration: v.durationMin || 0,
                charge: v.charge,
                paid: v.isPaid ? 'Yes' : 'No',
            });
        });
        // Download
        const buf = await wb.xlsx.writeBuffer();
        const blob = new Blob([buf], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = 'PhyJio_Visits.xlsx';
        a.click();
        URL.revokeObjectURL(url);
    }
    function markAllPaid() {
        if (!pid)
            return alert('Select a patient first');
        visits.filter(v => v.patientId === pid && !v.isPaid && v.status === 'completed')
            .forEach(v => updateVisit(v.id, { isPaid: true }));
        generateBill();
    }
    function sendOnWhatsApp() {
        if (!bill)
            return;
        window.open(`https://wa.me/?text=${encodeURIComponent(bill)}`, '_blank');
    }
    return (_jsxs("div", { style: { padding: 16 }, children: [_jsx("h2", { style: { fontSize: 22, fontWeight: 800, paddingTop: 12, marginBottom: 16 }, children: "Billing" }), _jsx("label", { style: { fontSize: 13, fontWeight: 600, color: 'var(--text-muted)', marginBottom: 6, display: 'block' }, children: "Select Patient" }), _jsxs("select", { value: pid, onChange: e => { setPid(e.target.value); setBill(null); }, style: { width: '100%', padding: '13px 16px', borderRadius: 12, border: '1px solid var(--border)', fontSize: 15, background: '#fff', marginBottom: 16 }, children: [_jsx("option", { value: '', children: "\u2014 All Patients \u2014" }), patients.filter(p => p.isActive).map(p => _jsx("option", { value: p.id, children: p.fullName }, p.id))] }), _jsx("button", { onClick: generateBill, style: { width: '100%', height: 56, borderRadius: 14, background: 'var(--teal)', color: '#fff', fontSize: 17, fontWeight: 700, marginBottom: 10, boxShadow: '0 4px 14px rgba(0,128,128,0.3)' }, children: "\uD83E\uDDFE Generate Bill" }), _jsx("button", { onClick: exportExcel, style: { width: '100%', height: 52, borderRadius: 14, background: '#fff', border: '1px solid var(--border)', color: 'var(--text)', fontSize: 15, fontWeight: 600, marginBottom: 10 }, children: "\uD83D\uDCCA Export to Excel (.xlsx)" }), _jsx("button", { onClick: markAllPaid, style: { width: '100%', height: 52, borderRadius: 14, background: '#E8FFF3', border: '1px solid var(--success)', color: '#1A6B3A', fontSize: 15, fontWeight: 600, marginBottom: 16 }, children: "\u2713 Mark All Visits as Paid" }), bill && (_jsxs(_Fragment, { children: [_jsx("pre", { style: { background: '#fff', borderRadius: 14, padding: 16, overflowX: 'auto', fontSize: 12, lineHeight: 1.9, boxShadow: 'var(--shadow)', fontFamily: 'monospace', whiteSpace: 'pre-wrap', wordBreak: 'break-all', marginBottom: 12 }, children: bill }), _jsx("button", { onClick: sendOnWhatsApp, style: { width: '100%', height: 52, borderRadius: 14, background: '#25D366', color: '#fff', fontSize: 16, fontWeight: 700, boxShadow: '0 4px 14px rgba(37,211,102,0.3)' }, children: "\uD83D\uDCAC Share Bill via WhatsApp" })] }))] }));
}
