import React, { useState } from 'react'
import { useDataStore } from '../store/dataStore'
import { useLocation } from 'react-router-dom'
import ExcelJS from 'exceljs'

export default function Billing() {
  const { patients, visits, updateVisit } = useDataStore()
  const location = useLocation()
  const pre      = location.state?.patient
  const [pid,  setPid]  = useState(pre?.id || '')
  const [bill, setBill] = useState<string | null>(null)

  const patient = patients.find(p => p.id === pid)

  function generateBill() {
    if (!pid) return alert('Please select a patient')
    const pvs   = visits.filter(v => v.patientId === pid && v.status === 'completed')
    const total = pvs.reduce((s, v) => s + v.charge, 0)
    const paid  = pvs.filter(v => v.isPaid).reduce((s, v) => s + v.charge, 0)
    const rows  = pvs.map((v, i) => {
      const d = new Date(v.startTime).toLocaleDateString('en-IN')
      const dur = v.durationMin ? `${v.durationMin}m` : '—'
      return `${String(i+1).padEnd(3)} ${d.padEnd(14)} ${dur.padEnd(6)} ₹${v.charge}`
    })
    setBill([
      `════════════════════════════════════════`,
      `   🩺  PhyJio | Home Physiotherapy`,
      `              INVOICE`,
      `════════════════════════════════════════`,
      `Patient : ${patient?.fullName}`,
      `Age     : ${patient?.age} years`,
      `Ailment : ${patient?.ailment}`,
      `Date    : ${new Date().toLocaleDateString('en-IN')}`,
      `────────────────────────────────────────`,
      `No. Date           Dur    Amount`,
      `────────────────────────────────────────`,
      ...rows,
      `────────────────────────────────────────`,
      `TOTAL BILLED :           ₹${total}`,
      `Amount Paid  :           ₹${paid}`,
      `BALANCE DUE  :           ₹${total - paid}`,
      `════════════════════════════════════════`,
      `  Generated by PhyJio`,
      `  ${new Date().toLocaleString('en-IN')}`,
      `════════════════════════════════════════`,
    ].join('\n'))
  }

  async function exportExcel() {
    const wb = new ExcelJS.Workbook()
    const ws = wb.addWorksheet('PhyJio Visits')
    ws.columns = [
      { header: 'Date',     key: 'date',     width: 16 },
      { header: 'Patient',  key: 'patient',  width: 24 },
      { header: 'Ailment',  key: 'ailment',  width: 20 },
      { header: 'Duration', key: 'duration', width: 12 },
      { header: 'Charge',   key: 'charge',   width: 12 },
      { header: 'Paid',     key: 'paid',     width: 10 },
    ]
    ws.getRow(1).eachCell(cell => {
      cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFDD2A7B' } }
      cell.font = { bold: true, color: { argb: 'FFFFFFFF' } }
    })
    const src = pid
      ? visits.filter(v => v.patientId === pid && v.status === 'completed')
      : visits.filter(v => v.status === 'completed')
    src.forEach(v => {
      const p = patients.find(x => x.id === v.patientId)
      ws.addRow({
        date: new Date(v.startTime).toLocaleDateString('en-IN'),
        patient: p?.fullName || 'Unknown',
        ailment: p?.ailment || '—',
        duration: v.durationMin || 0,
        charge: v.charge,
        paid: v.isPaid ? 'Yes' : 'No',
      })
    })
    const buf  = await wb.xlsx.writeBuffer()
    const blob = new Blob([buf], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' })
    const url  = URL.createObjectURL(blob)
    const a    = document.createElement('a')
    a.href = url; a.download = 'PhyJio_Visits.xlsx'; a.click()
    URL.revokeObjectURL(url)
  }

  function markAllPaid() {
    if (!pid) return alert('Select a patient first')
    visits.filter(v => v.patientId === pid && !v.isPaid && v.status === 'completed')
          .forEach(v => updateVisit(v.id, { isPaid: true }))
    generateBill()
  }

  const btnBase: React.CSSProperties = {
    width: '100%', padding: '16px 0', borderRadius: 18,
    fontSize: 16, fontWeight: 700, marginBottom: 10, display: 'flex',
    alignItems: 'center', justifyContent: 'center', gap: 8, border: 'none',
  }

  return (
    <div style={{ background: 'var(--bg)', minHeight: '100%', paddingBottom: 100 }}>

      {/* ── Header ── */}
      <div style={{ padding: '56px 20px 20px', background: 'var(--surface)', borderBottom: '0.5px solid var(--separator)', marginBottom: 24 }}>
        <h1 style={{ fontSize: 34, fontWeight: 800, letterSpacing: -0.5 }}>Billing</h1>
      </div>

      <div style={{ padding: '0 20px' }}>

        {/* Patient Selector */}
        <p style={{ fontSize: 13, fontWeight: 700, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: 0.8, marginBottom: 10 }}>
          Patient
        </p>
        <div style={{
          background: 'var(--surface)', borderRadius: 20,
          padding: '4px 16px', boxShadow: 'var(--shadow)', marginBottom: 24,
          position: 'relative',
        }}>
          <select
            value={pid}
            onChange={e => { setPid(e.target.value); setBill(null) }}
            style={{
              width: '100%', padding: '16px 0', fontSize: 17, color: 'var(--text)',
              background: 'transparent', border: 'none', outline: 'none',
              cursor: 'pointer', WebkitAppearance: 'none', appearance: 'none',
            }}>
            <option value=''>— Select patient —</option>
            {patients.filter(p => p.isActive).map(p => (
              <option key={p.id} value={p.id}>{p.fullName}</option>
            ))}
          </select>
          <span style={{ position: 'absolute', right: 16, top: '50%', transform: 'translateY(-50%)', color: 'var(--text-muted)', pointerEvents: 'none' }}>⌄</span>
        </div>

        {/* ── Action Buttons ── */}
        <button onClick={generateBill}
          style={{ ...btnBase, background: 'var(--ig-gradient)', color: '#fff', boxShadow: '0 6px 20px rgba(221,42,123,0.32)' }}>
          🧾 Generate Bill
        </button>

        <button onClick={exportExcel}
          style={{ ...btnBase, background: 'var(--surface)', color: 'var(--text)', boxShadow: 'var(--shadow)' }}>
          📊 Export to Excel (.xlsx)
        </button>

        <button onClick={markAllPaid}
          style={{ ...btnBase, background: 'rgba(52,199,89,0.10)', color: 'var(--success)', border: '1px solid rgba(52,199,89,0.25)', marginBottom: 24 }}>
          ✓ Mark All as Paid
        </button>

        {/* ── Bill Preview ── */}
        {bill && (
          <>
            <div style={{
              background: 'var(--surface)', borderRadius: 20,
              padding: '18px 16px', boxShadow: 'var(--shadow)',
              marginBottom: 14, overflow: 'hidden',
            }}>
              <pre style={{
                fontSize: 12, lineHeight: 1.9, fontFamily: 'monospace',
                whiteSpace: 'pre-wrap', wordBreak: 'break-all', color: 'var(--text)',
                overflowX: 'auto',
              }}>{bill}</pre>
            </div>
            <button
              onClick={() => window.open(`https://wa.me/?text=${encodeURIComponent(bill)}`, '_blank')}
              style={{ ...btnBase, background: '#25D366', color: '#fff', boxShadow: '0 6px 18px rgba(37,211,102,0.30)' }}>
              💬 Share via WhatsApp
            </button>
          </>
        )}

      </div>
    </div>
  )
}
