import React, { useState } from 'react'
import { useDataStore } from '../store/dataStore'
import { useLocation } from 'react-router-dom'
import ExcelJS from 'exceljs'

export default function Billing() {
  const { patients, visits, updateVisit } = useDataStore()
  const location  = useLocation()
  const pre       = location.state?.patient
  const [pid, setPid]   = useState(pre?.id || '')
  const [bill, setBill] = useState<string|null>(null)

  const patient = patients.find(p => p.id === pid)

  function generateBill() {
    if (!pid) return alert('Please select a patient')
    const pvs   = visits.filter(v => v.patientId === pid && v.status === 'completed')
    const total = pvs.reduce((s, v) => s + v.charge, 0)
    const paid  = pvs.filter(v => v.isPaid).reduce((s, v) => s + v.charge, 0)

    const rows = pvs.map((v, i) => {
      const dt  = new Date(v.startTime)
      const date = dt.toLocaleDateString('en-IN')
      const dur  = v.durationMin ? `${v.durationMin}m` : '—'
      return `${String(i+1).padEnd(3)} ${date.padEnd(14)} ${dur.padEnd(6)} ₹${v.charge}`
    })

    setBill([
      `════════════════════════════════════════`,
      `   🩺  PhyJio | Home Physiotherapy`,
      `              INVOICE`,
      `════════════════════════════════════════`,
      `Patient : ${patient?.fullName}`,
      `Age     : ${patient?.age} years`,
      `Ailment : ${patient?.ailment}`,
      `Date    : ${new Date().toLocaleDateString('en-IN')}`,
      `────────────────────────────────────────`,
      `No. Date           Dur    Amount`,
      `────────────────────────────────────────`,
      ...rows,
      `────────────────────────────────────────`,
      `TOTAL BILLED :           ₹${total}`,
      `Amount Paid  :           ₹${paid}`,
      `BALANCE DUE  :           ₹${total - paid}`,
      `════════════════════════════════════════`,
      `  Generated by PhyJio`,
      `  ${new Date().toLocaleString('en-IN')}`,
      `════════════════════════════════════════`,
    ].join('\n'))
  }

  async function exportExcel() {
    const wb = new ExcelJS.Workbook()
    const ws = wb.addWorksheet('PhyJio Visits')
    ws.columns = [
      { header:'Date',     key:'date',     width:16 },
      { header:'Patient',  key:'patient',  width:24 },
      { header:'Ailment',  key:'ailment',  width:20 },
      { header:'Duration', key:'duration', width:12 },
      { header:'Charge',   key:'charge',   width:12 },
      { header:'Paid',     key:'paid',     width:10 },
    ]
    // Style header row
    ws.getRow(1).eachCell(cell => {
      cell.fill = { type:'pattern', pattern:'solid', fgColor:{ argb:'FF008080' } }
      cell.font = { bold:true, color:{ argb:'FFFFFFFF' } }
    })
    // Add data
    const src = pid
      ? visits.filter(v => v.patientId === pid && v.status === 'completed')
      : visits.filter(v => v.status === 'completed')
    src.forEach(v => {
      const p = patients.find(x => x.id === v.patientId)
      ws.addRow({
        date:     new Date(v.startTime).toLocaleDateString('en-IN'),
        patient:  p?.fullName || 'Unknown',
        ailment:  p?.ailment  || '—',
        duration: v.durationMin || 0,
        charge:   v.charge,
        paid:     v.isPaid ? 'Yes' : 'No',
      })
    })
    // Download
    const buf  = await wb.xlsx.writeBuffer()
    const blob = new Blob([buf], { type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' })
    const url  = URL.createObjectURL(blob)
    const a    = document.createElement('a')
    a.href     = url
    a.download = 'PhyJio_Visits.xlsx'
    a.click()
    URL.revokeObjectURL(url)
  }

  function markAllPaid() {
    if (!pid) return alert('Select a patient first')
    visits.filter(v => v.patientId === pid && !v.isPaid && v.status === 'completed')
          .forEach(v => updateVisit(v.id, { isPaid:true }))
    generateBill()
  }

  function sendOnWhatsApp() {
    if (!bill) return
    window.open(`https://wa.me/?text=${encodeURIComponent(bill)}`, '_blank')
  }

  return (
    <div style={{ padding:16 }}>
      <h2 style={{ fontSize:22, fontWeight:800, paddingTop:12, marginBottom:16 }}>Billing</h2>

      <label style={{ fontSize:13, fontWeight:600, color:'var(--text-muted)', marginBottom:6, display:'block' }}>Select Patient</label>
      <select value={pid} onChange={e => { setPid(e.target.value); setBill(null) }}
        style={{ width:'100%', padding:'13px 16px', borderRadius:12, border:'1px solid var(--border)', fontSize:15, background:'#fff', marginBottom:16 }}>
        <option value=''>— All Patients —</option>
        {patients.filter(p=>p.isActive).map(p => <option key={p.id} value={p.id}>{p.fullName}</option>)}
      </select>

      <button onClick={generateBill}
        style={{ width:'100%', height:56, borderRadius:14, background:'var(--teal)', color:'#fff', fontSize:17, fontWeight:700, marginBottom:10, boxShadow:'0 4px 14px rgba(0,128,128,0.3)' }}>
        🧾 Generate Bill
      </button>

      <button onClick={exportExcel}
        style={{ width:'100%', height:52, borderRadius:14, background:'#fff', border:'1px solid var(--border)', color:'var(--text)', fontSize:15, fontWeight:600, marginBottom:10 }}>
        📊 Export to Excel (.xlsx)
      </button>

      <button onClick={markAllPaid}
        style={{ width:'100%', height:52, borderRadius:14, background:'#E8FFF3', border:'1px solid var(--success)', color:'#1A6B3A', fontSize:15, fontWeight:600, marginBottom:16 }}>
        ✓ Mark All Visits as Paid
      </button>

      {bill && (
        <>
          <pre style={{ background:'#fff', borderRadius:14, padding:16, overflowX:'auto', fontSize:12, lineHeight:1.9, boxShadow:'var(--shadow)', fontFamily:'monospace', whiteSpace:'pre-wrap', wordBreak:'break-all', marginBottom:12 }}>
            {bill}
          </pre>
          <button onClick={sendOnWhatsApp}
            style={{ width:'100%', height:52, borderRadius:14, background:'#25D366', color:'#fff', fontSize:16, fontWeight:700, boxShadow:'0 4px 14px rgba(37,211,102,0.3)' }}>
            💬 Share Bill via WhatsApp
          </button>
        </>
      )}
    </div>
  )
}