import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { useDataStore } from '../store/dataStore';
import { useNavigate } from 'react-router-dom';
export default function PatientList() {
    const { patients } = useDataStore();
    const navigate = useNavigate();
    const [q, setQ] = useState('');
    const list = patients.filter(p => p.isActive &&
        (p.fullName.toLowerCase().includes(q.toLowerCase()) ||
            p.ailment.toLowerCase().includes(q.toLowerCase())));
    return (_jsxs("div", { style: { padding: 16 }, children: [_jsxs("div", { style: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', paddingTop: 12, marginBottom: 16 }, children: [_jsx("h2", { style: { fontSize: 22, fontWeight: 800 }, children: "Patients" }), _jsx("button", { onClick: () => navigate('/phyjio/patients/add'), style: { width: 44, height: 44, borderRadius: 22, background: 'var(--teal)', color: '#fff', fontSize: 26, display: 'flex', alignItems: 'center', justifyContent: 'center' }, children: "+" })] }), _jsx("input", { value: q, onChange: e => setQ(e.target.value), placeholder: "\uD83D\uDD0D  Search name or ailment...", style: { width: '100%', padding: '12px 16px', borderRadius: 12, border: '1px solid var(--border)', fontSize: 15, marginBottom: 16, background: '#fff' } }), list.length === 0 ? (_jsxs("div", { style: { textAlign: 'center', padding: 48, color: 'var(--text-muted)' }, children: [_jsx("p", { style: { fontSize: 48, marginBottom: 12 }, children: "\uD83D\uDC65" }), _jsx("p", { style: { fontWeight: 600 }, children: "No patients yet" }), _jsx("p", { style: { fontSize: 13, marginTop: 4 }, children: "Tap + to add your first patient" })] })) : list.map(p => (_jsxs("div", { onClick: () => navigate(`/phyjio/patients/${p.id}`), style: { background: '#fff', borderRadius: 14, padding: 16, marginBottom: 12, boxShadow: 'var(--shadow)', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: 14 }, children: [_jsx("div", { style: { width: 50, height: 50, borderRadius: 25, background: 'var(--teal)', color: '#fff', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 22, fontWeight: 700, flexShrink: 0 }, children: p.fullName.charAt(0).toUpperCase() }), _jsxs("div", { style: { flex: 1 }, children: [_jsx("p", { style: { fontWeight: 700, fontSize: 16 }, children: p.fullName }), _jsxs("p", { style: { color: 'var(--text-muted)', fontSize: 13 }, children: [p.ailment, " \u2022 ", p.age, " yrs"] }), _jsxs("p", { style: { color: 'var(--teal)', fontSize: 12, fontWeight: 600, marginTop: 2 }, children: ["\u20B9", p.chargePerVisit, "/visit"] })] }), _jsx("span", { style: { color: 'var(--text-muted)', fontSize: 22 }, children: "\u203A" })] }, p.id)))] }));
}
